import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex justify-center space-x-2 xl:space-x-20 bg-pink-300">
        <Link href='/' className="text-black-500">Home</Link><br/>
        <Link href='/about' className="text-black-500">About</Link><br/>
        <Link href='/contact' className="text-black-500">Contact</Link>
        </div>
        {children}
        </body>
    </html>
  );
}
